spring.application.name=esre-backend
spring.datasource.url=jdbc:postgresql://localhost:4321/esre
spring.datasource.username=postgres
spring.datasource.password=HOLA123

#hibernate properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
